# Setting the river geometry and model parameters

g  : 9.81
nu : 0.000001

q_min  : 100.     # minimun discharge m3/s
q_max  : 600.     # maximum discharge m3/s
t_q    : 20.      # time from min discharge to maximum discharge (hour)
chlen  : 6000     # length of river reach (m)
wid    : 70.      # channel width (m)
snm    : 0.028    # mannings roughness coefs
ib     : 0.005    # bed slope
spec   : 1.65
diam   : 0.04     # sediment diameter
tsc    : 0.05
poro   : 0.4
qbin   : 0.01     #sediment supply m2/s

i_vis : 0

output_interval : 4  # unit is hour
hyd_cycle : 50

nx : 200    # number of grid
dt : 0.5    # computational time step (sec)