# Setting the river geometry and model parameters

g  : 9.81
nu : 0.000001

q_min  : 500.     # minimun discharge m3/s
q_max  : 500.     # maximum discharge m3/s
t_q    : 20.      # time from min discharge to maximum discharge (hour)
chlen  : 2000     # length of river reach (m)
wid    : 200.      # channel width (m)
snm    : 0.03    # mannings roughness coefs
ib     : 0.002    # bed slope
spec   : 1.65
diam   : 0.002     # sediment diameter
poro   : 0.4
qbin   : 0.01     #bedload supply m2/s

i_qbin : 0

output_interval : 0.1  # unit is hour
morpho_start : 0.5  # unit is hour
etime : 50          # unit is hour

nx : 200    # number of grid
dt : 0.2    # computational time step (sec)

path_op : "fig/"